---
- name: Create databases
  mysql_db:
    name: "{{ item }}"
  with_items: "{{ mariadb_databases }}"
  when: mariadb_databases is defined

- name: Create users
  mysql_user:
    login_user: "root"
    login_password: "{{ mariadb_root_password }}"
    login_host: "127.0.0.1"
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    host: "{{ item.host }}"
    state: "present"
    priv: "{{ item.priv }}"
  with_items: "{{ mariadb_users }}"
  when: mariadb_users is defined
